updated hammer image
redhat-performance/JetSki pull request #143
Opened 2021-05-14 14:29 UTC by mukrishn

# Description

I could reproduce the issue in centos7, updated them to use centos:8. 

Fixes #142 

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally
- [ ] Test B

**Test Configuration**:

- Versions: 
- Hardware: Dell R640

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2021-05-14 14:30 UTC, mukrishn commented
@akiselev1 could you test this patch and let us know ?

2021-05-14 14:47 UTC, smalleni commented on ansible-ipi-install/roles/bootstrap/files/Dockerfile
> +FROM centos:8
Is this using quay.io then?

2021-05-14 14:47 UTC, smalleni commented on ansible-ipi-install/roles/bootstrap/files/Dockerfile
> +RUN yum install -y https://yum.theforeman.org/releases/2.1/el8/x86_64/foreman-release.rpm
Lets condense into one RUN/yum command, would result in fewer layers in the image.

2021-05-14 14:51 UTC, akiselev1 commented
> @akiselev1 could you test this patch and let us know ?

Yes, the fix works for me. I can try the final version as well - let me know.

2021-05-14 14:53 UTC, mukrishn commented on ansible-ipi-install/roles/bootstrap/files/Dockerfile
> +FROM centos:8
I think it still goes to docker.io

2021-05-14 15:03 UTC, smalleni requested changes

2021-05-14 15:03 UTC, smalleni commented on ansible-ipi-install/roles/bootstrap/files/Dockerfile
> +RUN yum install -y https://yum.theforeman.org/releases/2.1/el8/x86_64/foreman-release.rpm
Move to dnf as it is centos8

2021-05-14 15:35 UTC, akiselev1 commented
The new version works fine as well.

2021-05-17 16:21 UTC, smalleni approved these changes

2021-05-17 16:21 UTC, merged